config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'logout'

  get 'faq/hello', to: 'faqs#hello'

  get 'article/index', to: 'articles#index'
  get 'article/extra_news_send/:id', to: 'articles#extra_news_send', as: 'article_extra_news_send'

  resources :sessions, only: %i[create destroy]
  resources :users
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/categories.rb
class Categories < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  encrypts :slack_webhook_url

  SLACK_URL_REGEX = /(https:\/\/hooks.slack.com\/services)(.*)/
  
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.update(user_params)
      end
    end
    
    private

    def user_params_from_auth_hash(auth_hash)
      {
        name: auth_hash.info.name,
        email: auth_hash.info.email,
        image: auth_hash.info.image,
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :check_logged_in

  def check_logged_in
    return if current_user

    redirect_to root_path
  end

  def check_for_slack_webhook_url
    return if current_user.slack_webhook_url

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_for_slack_webhook_url, only: [:extra_news_send]
  before_action :fetch_article, only: [:extra_news_send, :edit, :update]

  def index
    @articles = Article.all()
  end

  def edit
    @user = @current_user
  end

  def update
    if @article.update!(article_params)
      redirect_to article_index_path
    else
      render 'edit'
    end
  end

  def extra_news_send
    message = {
      blocks: [
        {
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": @article.title,
          }
        },
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": @article.content
          }
        }
      ]
    }
    SlackUtility.send(
      current_user.slack_webhook_url,
      message
    )

    redirect_to article_index_path
  end

  private

    def fetch_article
      @article = Article.find(params[:id])
    rescue => e
      render status: :not_found, json: { error: e }
    end

    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController  
  def hello
    client = Slack::Web::Client.new
    client.chat_postMessage(
      channel: ENV.fetch("SLACK_CHANNEL"),
      blocks: [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "今日も暑いね:watermelon: 無理せずがんばろう:smile:"
          }
        },
        {
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": "何をチェックする？",
            "emoji": true
          }
        },
        {
          "type": "actions",
          "elements": [
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "emoji": true,
                "text": "天気"
              },
              "style": "primary",
              "url": "https://www.jma.go.jp/jp/yoho/" # 気象庁HP
            },
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "emoji": true,
                "text": "カレンダー"
              },
              "style": "danger",
              "url": "https://calendar.google.com/" # Googleカレンダー
            },
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "emoji": true,
                "text": "ニュース"
              },
              "url": "https://news.google.co.jp/" # Googleニュース
            }
          ]
        }
      ]
    )

    redirect_to root_path
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  def hello
    client = Slack::Web::Client.new
    client.chat_postMessage(
      channel: ENV.fetch("SLACK_CHANNEL"),
      blocks: [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "今日も暑いね:watermelon: 無理せずがんばろう:smile:"
          }
        },
        {
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": "何をチェックする？",
            "emoji": true
          }
        },
        {
          "type": "actions",
          "elements": [
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "emoji": true,
                "text": "天気"
              },
              "style": "primary",
              "url": "https://www.jma.go.jp/jp/yoho/" # 気象庁HP
            },
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "emoji": true,
                "text": "カレンダー"
              },
              "style": "danger",
              "url": "https://calendar.google.com/" # Googleカレンダー
            },
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "emoji": true,
                "text": "ニュース"
              },
              "url": "https://news.google.co.jp/" # Googleニュース
            }
          ]
        }
      ]
    )

    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :check_logged_in, only: :index
  
  def index
  end
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_action :check_for_slack_webhook_url
  before_action :fetch_newspaper, only: [:extra_news_send]

  def index
    @newspapers = Newspaper.all()
  end

  def extra_news_send
    message = {
      blocks: [
        {
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": @newspaper.title,
          }
        },
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": @newspaper.content
          }
        }
      ]
    }
    SlackUtility.send(
      current_user.slack_webhook_url,
      message
    )

    redirect_to newspaper_index_path
  end

  private

    def fetch_newspaper
      @newspaper = Newspaper.find(params[:id])
    rescue => e
      render status: :not_found, json: { error: e }
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_logged_in, only: :create
  
  def create
    if (user = User.find_or_create_from_auth_hash(auth_hash))
      log_in user
    end
    redirect_to root_path
  end
   
  def destroy
    log_out
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_logged_in, only: :index
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attribute(:slack_webhook_url, user_params[:slack_webhook_url])
      flash[:success] = "Profile updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:slack_webhook_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return unless (user_id = session[:user_id])

    @current_user ||= User.find_by(id: user_id)
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/articles/edit.html.erb
<div class="container mt-4">
  <%= render(Articles::EditFormComponent.new(article: @article)) %>
</div>

app/views/articles/index.html.erb
<div class="container mt-4 p-2">
  <%= render(Articles::ListComponent.new(articles: @articles)) %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_sidebar.html.erb
<div class="p-3 text-white bg-dark sticky-top"  style="height: 100vh;">
  <%= link_to("Navbar", root_path, { class: "nav-link navbar-brand text-white" }) %>
  <ul class="nav navbar-nav-scroll flex-column p-2">
    <nav class="nav nav-pills flex-column">
      <%= link_to("掲載スケジュール", article_index_path, { class: "nav-link navbar-brand text-white" }) %>
      <%= link_to("一覧", article_index_path, { class: "nav-link text-white ms-3 my-1" }) %>
      <%= link_to("新規作成", root_path, { class: "nav-link text-white ms-3 my-1" }) %>
    </nav>
    <nav class="nav nav-pills flex-column">
      <%= link_to("新聞管理", root_path, { class: "nav-link navbar-brand text-white" }) %>
      <a class="nav-link text-white ms-3 my-1" href="#item-1-1">一覧</a>
      <a class="nav-link text-white ms-3 my-1" href="#item-1-2">新規作成</a>
    </nav>
    <nav class="nav nav-pills flex-column">
      <%= link_to("記事管理", article_index_path, { class: "nav-link navbar-brand text-white" }) %>
      <%= link_to("一覧", article_index_path, { class: "nav-link text-white ms-3 my-1" }) %>
      <%= link_to("新規作成", root_path, { class: "nav-link text-white ms-3 my-1" }) %>
    </nav>
  </ul>
  <div class="fixed-bottom d-flex p-4">
    <% if logged_in? %>
      <div class="dropdown">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <%= image_tag(current_user.image, size: "40x40") %>
        </button>
        <ul class="dropdown-menu">
          <li class="dropdown-item"><%= link_to "ログアウト", logout_path %></li>
          <li class="dropdown-item"><%= link_to "設定", edit_user_path(current_user) %></li>
        </ul>
      </div>
    <% else %>
      <%= link_to("ログイン", "/auth/google_oauth2", {method: :post}) %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

  </head>

  <body>
    <div class="row">
      <div class="col-3">
        <%= render 'layouts/sidebar' %>
      </div>
      <div class="col-8 p-0">
        <div class="overflow-scroll">
          <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container mt-4">
  <%= render(Users::EditFormComponent.new(user: @user)) %>
</div>